import { BaseExploration } from './base-exploration.js';
import { register } from './registry.js';
import { getGL } from '../renderer/webgl-context.js';
import { createProgram, getUniforms } from '../renderer/shader-utils.js';
import { drawFullscreenQuad } from '../renderer/fullscreen-quad.js';
import { fullscreenQuadVert } from '../shaders/fullscreen-quad.vert.js';
import { kleinianFrag } from '../shaders/kleinian.frag.js';

// Preset configurations
const PRESETS = {
  apollonian: {
    label: 'Apollonian Gasket',
    preset: 0,
    zoom: 6.0,
    centerX: 0.0,
    centerY: 0.0,
    // Generator uniforms not used by Apollonian (circle inversions are hardcoded)
    genA: [1, 0, 0, 0],
    genB: [1, 0, 0, 0],
    genA2: [0, 0, 1, 0],
    genB2: [0, 0, 1, 0]
  },
  schottky: {
    label: 'Schottky Group',
    preset: 1,
    zoom: 5.0,
    centerX: 0.0,
    centerY: 0.0,
    genA: [1, 0, 0, 0],
    genB: [1, 0, 0, 0],
    genA2: [0, 0, 1, 0],
    genB2: [0, 0, 1, 0]
  },
  maskit: {
    label: 'Maskit Slice',
    preset: 2,
    zoom: 6.0,
    centerX: 0.0,
    centerY: 1.0,
    // Maskit parametrization: generator a = [[mu, i],[i, 0]], generator b = [[1, 2],[0, 1]]
    // where mu = 2i (a good starting value on the boundary of the Maskit slice)
    // a coefficients: a=mu=(0,2), b=i=(0,1), c=i=(0,1), d=0=(0,0)
    genA: [0, 2, 0, 1],
    genA2: [0, 1, 0, 0],
    // b coefficients: a=1=(1,0), b=2=(2,0), c=0=(0,0), d=1=(1,0)
    genB: [1, 0, 2, 0],
    genB2: [0, 0, 1, 0]
  }
};

class KleinianExploration extends BaseExploration {
  static id = 'kleinian';
  static title = 'Kleinian Group';
  static description = 'Limit sets of Kleinian groups and Möbius transformations';
  static category = 'fractal';
  static formulaShort = 'z \u2192 (az+b)/(cz+d)';
  static formula = `<h3>Kleinian Group Limit Sets</h3>
<div class="formula-block">
M\u00F6bius transform: z \u2192 \u2009(az + b) / (cz + d)<br>
a, b, c, d \u2208 \u2102, &nbsp; ad \u2212 bc = 1<br>
Group generated by transformations A, B and their inverses
</div>
<p>A <strong>Kleinian group</strong> is a discrete subgroup of PSL(2,\u2102), the group of M\u00F6bius transformations of the Riemann sphere. Each M\u00F6bius transformation is a fractional linear map z \u2192 (az+b)/(cz+d) with complex coefficients.</p>
<p>The <strong>limit set</strong> \u039B is the set of accumulation points of the orbit of any point under the group action. For finitely generated groups, the limit set is typically a fractal \u2014 a Cantor set, a circle, or an intricate curve.</p>
<p>This exploration visualizes three classic examples:</p>
<ul>
  <li><strong>Apollonian Gasket</strong> \u2014 generated by inversions in four mutually tangent circles</li>
  <li><strong>Schottky Group</strong> \u2014 generated by M\u00F6bius maps pairing disjoint circles</li>
  <li><strong>Maskit Slice</strong> \u2014 the boundary of the Maskit parametrization of once-punctured torus groups</li>
</ul>`;
  static tutorial = `<h3>How Kleinian Limit Sets are Computed</h3>
<p>The algorithm depends on the type of group:</p>
<h4>Circle Inversions (Apollonian Gasket)</h4>
<p>For each pixel, we repeatedly invert the point through a configuration of circles. A circle inversion maps a point z through a circle with center c and radius r:</p>
<pre><code class="language-js">// Circle inversion
function invert(z, center, r) {
  const dz = z - center;
  return center + (r*r / |dz|^2) * dz;
}

// For each pixel z:
for (let i = 0; i < maxIter; i++) {
  // Find a circle whose interior contains z
  // and invert through it
  if (inside(circle_k)) {
    z = invert(z, center_k, radius_k);
  } else {
    break; // z is in the fundamental domain
  }
}</code></pre>
<h4>M\u00F6bius Generators (Maskit Slice)</h4>
<p>Given two generators A and B (and their inverses A\u207B\u00B9, B\u207B\u00B9), we apply whichever transform pulls the point closest to the limit set:</p>
<pre><code class="language-js">// Mobius transform: z -> (a*z + b) / (c*z + d)
function mobius(z, a, b, c, d) {
  return (a*z + b) / (c*z + d);
}

// For each pixel, iterate:
for (let i = 0; i < maxIter; i++) {
  // Apply A, A^-1, B, B^-1
  // Pick the one that minimizes |Im(z)|
  z = bestTransform(z);
}</code></pre>
<p>Pixels are colored by iteration depth and orbit trap distance \u2014 how close the orbit passes to the limit set.</p>
<h4>PSL(2,\u2102) and Discreteness</h4>
<p>The group of all M\u00F6bius transforms with ad\u2212bc=1 is PSL(2,\u2102). A Kleinian group is a <em>discrete</em> subgroup. Discreteness means orbits don\u2019t fill space \u2014 they accumulate on a fractal limit set. The complement of the limit set is the <em>ordinary set</em> (or domain of discontinuity), where the group acts properly discontinuously.</p>`;

  constructor(canvas, controlsContainer) {
    super(canvas, controlsContainer);
    const defaultPreset = PRESETS.apollonian;
    this.params = {
      preset: 'apollonian',
      presetIndex: defaultPreset.preset,
      maxIter: 200,
      colorScheme: 0,
      zoom: defaultPreset.zoom,
      centerX: defaultPreset.centerX,
      centerY: defaultPreset.centerY,
      genA: [...defaultPreset.genA],
      genB: [...defaultPreset.genB],
      genA2: [...defaultPreset.genA2],
      genB2: [...defaultPreset.genB2]
    };
    this.gl = null;
    this.program = null;
    this.uniforms = null;
    this._isDragging = false;
    this._dragStart = null;
    this._dragCenterStart = null;
    this._handlers = null;
  }

  getControls() {
    return [
      {
        type: 'select', key: 'preset', label: 'Preset',
        options: [
          { value: 'apollonian', label: 'Apollonian Gasket' },
          { value: 'schottky', label: 'Schottky Group' },
          { value: 'maskit', label: 'Maskit Slice' }
        ],
        value: this.params.preset
      },
      { type: 'slider', key: 'maxIter', label: 'Max Iterations', min: 20, max: 500, step: 10, value: this.params.maxIter },
      {
        type: 'select', key: 'colorScheme', label: 'Colors',
        options: [
          { value: 0, label: 'Nebula' },
          { value: 1, label: 'Fire' },
          { value: 2, label: 'Ocean' },
          { value: 3, label: 'Grayscale' },
          { value: 4, label: 'Viridis' },
          { value: 5, label: 'Plasma' }
        ],
        value: this.params.colorScheme
      },
      { type: 'separator' },
      { type: 'button', key: 'reset', label: 'Reset View', action: 'reset' },
      { type: 'description', text: 'Drag to pan, scroll to zoom. Select a preset to explore different Kleinian groups.' },
      { type: 'button', key: 'showInfo', label: 'Show Math', action: 'showInfo' }
    ];
  }

  activate() {
    this.gl = getGL(this.canvas);
    this.program = createProgram(this.gl, fullscreenQuadVert, kleinianFrag);
    this.uniforms = getUniforms(this.gl, this.program, [
      'u_resolution', 'u_center', 'u_zoom', 'u_maxIter',
      'u_colorScheme', 'u_preset',
      'u_genA', 'u_genB', 'u_genA2', 'u_genB2'
    ]);

    const onWheel = (e) => {
      e.preventDefault();
      const rect = this.canvas.getBoundingClientRect();
      const mx = (e.clientX - rect.left) / rect.width;
      const my = 1.0 - (e.clientY - rect.top) / rect.height;
      const aspect = this.canvas.width / this.canvas.height;
      const worldX = this.params.centerX + (mx - 0.5) * this.params.zoom * aspect;
      const worldY = this.params.centerY + (my - 0.5) * this.params.zoom;
      const factor = e.deltaY > 0 ? 1.1 : 0.9;
      this.params.zoom *= factor;
      this.params.centerX = worldX - (mx - 0.5) * this.params.zoom * aspect;
      this.params.centerY = worldY - (my - 0.5) * this.params.zoom;
      this.scheduleRender();
    };

    const onMouseDown = (e) => {
      if (e.button === 0) {
        this._isDragging = true;
        this._dragStart = { x: e.clientX, y: e.clientY };
        this._dragCenterStart = { x: this.params.centerX, y: this.params.centerY };
        this.canvas.style.cursor = 'grabbing';
      }
    };

    const onMouseMove = (e) => {
      if (!this._isDragging) return;
      const rect = this.canvas.getBoundingClientRect();
      const dx = (e.clientX - this._dragStart.x) / rect.width;
      const dy = (e.clientY - this._dragStart.y) / rect.height;
      const aspect = this.canvas.width / this.canvas.height;
      this.params.centerX = this._dragCenterStart.x - dx * this.params.zoom * aspect;
      this.params.centerY = this._dragCenterStart.y + dy * this.params.zoom;
      this.scheduleRender();
    };

    const onMouseUp = () => {
      this._isDragging = false;
      this.canvas.style.cursor = '';
    };

    this.canvas.addEventListener('wheel', onWheel, { passive: false });
    this.canvas.addEventListener('mousedown', onMouseDown);
    window.addEventListener('mousemove', onMouseMove);
    window.addEventListener('mouseup', onMouseUp);
    this._handlers = { onWheel, onMouseDown, onMouseMove, onMouseUp };
  }

  deactivate() {
    super.deactivate();
    if (this._handlers) {
      this.canvas.removeEventListener('wheel', this._handlers.onWheel);
      this.canvas.removeEventListener('mousedown', this._handlers.onMouseDown);
      window.removeEventListener('mousemove', this._handlers.onMouseMove);
      window.removeEventListener('mouseup', this._handlers.onMouseUp);
      this._handlers = null;
    }
    if (this.program && this.gl) {
      this.gl.deleteProgram(this.program);
      this.program = null;
    }
  }

  onParamChange(key, value) {
    if (key === 'preset') {
      this._applyPreset(value);
    } else {
      this.params[key] = value;
    }
    this.scheduleRender();
  }

  _applyPreset(presetKey) {
    const p = PRESETS[presetKey];
    if (!p) return;
    this.params.preset = presetKey;
    this.params.presetIndex = p.preset;
    this.params.zoom = p.zoom;
    this.params.centerX = p.centerX;
    this.params.centerY = p.centerY;
    this.params.genA = [...p.genA];
    this.params.genB = [...p.genB];
    this.params.genA2 = [...p.genA2];
    this.params.genB2 = [...p.genB2];
  }

  reset() {
    this._applyPreset(this.params.preset);
    this.params.maxIter = 200;
    this.params.colorScheme = 0;
    this.scheduleRender();
  }

  resize() { this.scheduleRender(); }

  render() {
    const gl = this.gl;
    if (!gl || !this.program) return;

    gl.viewport(0, 0, this.canvas.width, this.canvas.height);
    gl.useProgram(this.program);

    gl.uniform2f(this.uniforms.u_resolution, this.canvas.width, this.canvas.height);
    gl.uniform2f(this.uniforms.u_center, this.params.centerX, this.params.centerY);
    gl.uniform1f(this.uniforms.u_zoom, this.params.zoom);
    gl.uniform1i(this.uniforms.u_maxIter, this.params.maxIter);
    gl.uniform1i(this.uniforms.u_colorScheme, this.params.colorScheme);
    gl.uniform1i(this.uniforms.u_preset, this.params.presetIndex);

    gl.uniform4f(this.uniforms.u_genA,
      this.params.genA[0], this.params.genA[1],
      this.params.genA[2], this.params.genA[3]);
    gl.uniform4f(this.uniforms.u_genB,
      this.params.genB[0], this.params.genB[1],
      this.params.genB[2], this.params.genB[3]);
    gl.uniform4f(this.uniforms.u_genA2,
      this.params.genA2[0], this.params.genA2[1],
      this.params.genA2[2], this.params.genA2[3]);
    gl.uniform4f(this.uniforms.u_genB2,
      this.params.genB2[0], this.params.genB2[1],
      this.params.genB2[2], this.params.genB2[3]);

    drawFullscreenQuad(gl);
  }
}

register(KleinianExploration);
