import { BaseExploration } from './base-exploration.js';
import { register } from './registry.js';

class LissajousExploration extends BaseExploration {
  static id = 'lissajous';
  static title = 'Lissajous Figures';
  static description = 'Complex harmonic motion formed by perpendicular sine waves.';
  static category = 'parametric-curves';
  static tags = [
    'parametric-curves', 'parametric', 'beginner',
    'harmonic-motion', 'oscillation',
  ];
  static formulaShort = 'x = sin(at+&delta;), y = sin(bt)';
  static formula = `<h3>Lissajous Figures</h3>
<div class="formula-block">
x(t) = A&middot;sin(a&middot;t + &delta;)<br>
y(t) = A&middot;sin(b&middot;t)<br>
t &isin; [0, 2&pi;]
</div>
<p>Lissajous curves are the family of curves traced by a point whose coordinates oscillate
sinusoidally at (generally) different frequencies. When the frequency ratio a:b is rational
the curve closes; irrational ratios produce space-filling paths.</p>
<p>The <strong>phase shift &delta;</strong> rotates and morphs the figure. At &delta;&nbsp;=&nbsp;0 the curve
collapses to a line segment; at &delta;&nbsp;=&nbsp;&pi;/2 with a&nbsp;=&nbsp;b it becomes a circle.</p>`;
  static tutorial = `<h3>How Lissajous Figures Work</h3>
<p>The curve is generated by sampling t from 0 to 2&pi; and plotting:</p>
<pre><code class="language-js">for (let i = 0; i &lt;= steps; i++) {
  const t = (i / steps) * 2 * Math.PI;
  const x = A * Math.sin(a * t + delta);
  const y = A * Math.sin(b * t);
  // draw (x, y)
}</code></pre>
<p>Integer frequency ratios produce closed curves with a fixed number of lobes. Try a=3, b=2 for a
classic "figure-8" variant, or a=5, b=4 for a more complex knot.</p>`;
  static foundations = [];
  static extensions = ['unit-circle'];

  static guidedSteps = [
    {
      label: 'Circle (1:1)',
      description: 'Equal frequencies with a 90° phase shift make a perfect circle. This is the simplest Lissajous figure — both axes oscillate in sync.',
      params: { freqX: 1, freqY: 1, phase: 1.57, amplitude: 2, trailLength: 1.0 }
    },
    {
      label: 'Figure-Eight (1:2)',
      description: 'Y oscillates twice as fast as X. The curve crosses itself once, tracing a figure-eight. The frequency ratio determines how many loops appear.',
      params: { freqX: 1, freqY: 2, phase: 0, amplitude: 2, trailLength: 1.0 }
    },
    {
      label: 'Classic 3:2',
      description: 'The 3:2 ratio produces a pretzel-like knot. The curve closes after the least common multiple of cycles — 6 half-periods for this ratio.',
      params: { freqX: 3, freqY: 2, phase: 1.57, amplitude: 2, trailLength: 1.0 }
    },
    {
      label: 'Complex Knot (5:4)',
      description: 'Higher frequency ratios create more intricate crossings. Count the loops: the total is related to the sum and difference of the two frequencies.',
      params: { freqX: 5, freqY: 4, phase: 1.57, amplitude: 2, trailLength: 1.0 }
    },
    {
      label: 'Phase Sweep',
      description: 'Change the phase shift to 0 — the figure collapses to a diagonal line. Lissajous figures are maximally open at 90° phase and degenerate at 0° and 180°.',
      params: { freqX: 3, freqY: 2, phase: 0, amplitude: 2, trailLength: 1.0 }
    }
  ];

  constructor(canvas, controlsContainer) {
    super(canvas, controlsContainer);
    this.params = {
      freqX: 3,
      freqY: 2,
      phase: 1.57,
      amplitude: 2,
      trailLength: 1.0,
    };
    this.ctx = null;
    this.time = 0;
    this._lastFrame = 0;
  }

  getControls() {
    return [
      { type: 'slider', key: 'freqX', label: 'Frequency X (a)', min: 1, max: 10, step: 1, value: this.params.freqX },
      { type: 'slider', key: 'freqY', label: 'Frequency Y (b)', min: 1, max: 10, step: 1, value: this.params.freqY },
      { type: 'slider', key: 'phase', label: 'Phase Shift (\u03b4)', min: 0, max: 6.28, step: 0.01, value: this.params.phase },
      { type: 'slider', key: 'amplitude', label: 'Amplitude', min: 0.5, max: 4, step: 0.1, value: this.params.amplitude },
      { type: 'slider', key: 'trailLength', label: 'Trail Length', min: 0.1, max: 1, step: 0.05, value: this.params.trailLength },
      { type: 'separator' },
      { type: 'button', key: 'start', label: 'Animate', action: 'start' },
      { type: 'button', key: 'stop', label: 'Stop', action: 'stop' },
    ];
  }

  activate() {
    this.ctx = this.canvas.getContext('2d');
    this.time = 0;
    this._lastFrame = performance.now();
    this.render();
    this.start();
  }

  deactivate() {
    super.deactivate();
    this.ctx = null;
  }

  start() {
    super.start();
    this._lastFrame = performance.now();
    this._animate();
  }

  _animate() {
    if (!this.isRunning) return;
    const now = performance.now();
    this.time += (now - this._lastFrame) / 1000;
    this._lastFrame = now;
    this.updateAudio();
    this.render();
    this.animFrameId = requestAnimationFrame(() => this._animate());
  }

  onParamChange(key, value) {
    super.onParamChange(key, value);
    this._syncAudioParams();
    this.render();
  }

  reset() {
    this.time = 0;
    this.render();
  }

  resize(w, h) { this.render(); }

  // ── Audio ──

  setupAudio(audioCtx, masterGain) {
    this._audioCtx = audioCtx;
    this._oscX = audioCtx.createOscillator();
    this._oscY = audioCtx.createOscillator();
    this._gainX = audioCtx.createGain();
    this._gainY = audioCtx.createGain();
    this._gainX.gain.value = 0.5;
    this._gainY.gain.value = 0.5;
    this._syncAudioParams();
    this._oscX.connect(this._gainX);
    this._oscY.connect(this._gainY);
    this._gainX.connect(masterGain);
    this._gainY.connect(masterGain);
    this._oscX.start();
    this._oscY.start();
  }

  _syncAudioParams() {
    if (!this._oscX) return;
    const now = this._audioCtx.currentTime;
    this._oscX.frequency.setTargetAtTime(220 + (this.params.freqX || 1) * 20, now, 0.05);
    this._oscY.frequency.setTargetAtTime(220 + (this.params.freqY || 1) * 20, now, 0.05);
  }

  updateAudio() {}

  teardownAudio() {
    for (const osc of [this._oscX, this._oscY]) {
      if (osc) { try { osc.stop(); } catch { /* */ } osc.disconnect(); }
    }
    for (const g of [this._gainX, this._gainY]) {
      if (g) g.disconnect();
    }
    this._oscX = this._oscY = this._gainX = this._gainY = this._audioCtx = null;
  }

  render() {
    const ctx = this.ctx;
    if (!ctx) return;
    const { width: W, height: H } = this.canvas;
    const { freqX: a, freqY: b, phase: delta, amplitude: A, trailLength } = this.params;

    ctx.fillStyle = '#0f1117';
    ctx.fillRect(0, 0, W, H);

    const cx = W / 2;
    const cy = H / 2;
    const scale = Math.min(W, H) / 2 * 0.75 / Math.max(A, 1);

    // Axes
    ctx.strokeStyle = '#2a2d3a';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(0, cy); ctx.lineTo(W, cy);
    ctx.moveTo(cx, 0); ctx.lineTo(cx, H);
    ctx.stroke();

    // Full curve (faint)
    const steps = 600;
    const endT = 2 * Math.PI;
    ctx.strokeStyle = 'rgba(107, 124, 255, 0.35)';
    ctx.lineWidth = 1.5;
    ctx.beginPath();
    for (let i = 0; i <= steps; i++) {
      const t = (i / steps) * endT;
      const x = cx + A * Math.sin(a * t + delta) * scale;
      const y = cy - A * Math.sin(b * t) * scale;
      i === 0 ? ctx.moveTo(x, y) : ctx.lineTo(x, y);
    }
    ctx.stroke();

    // Animated trail
    if (this.isRunning || this.time > 0) {
      const trailEnd = this.time;
      const trailStart = Math.max(0, trailEnd - endT * trailLength);
      const trailSteps = 400;
      ctx.lineWidth = 2.5;
      ctx.beginPath();
      for (let i = 0; i <= trailSteps; i++) {
        const t = trailStart + (i / trailSteps) * (trailEnd - trailStart);
        const x = cx + A * Math.sin(a * t + delta) * scale;
        const y = cy - A * Math.sin(b * t) * scale;
        if (i === 0) ctx.moveTo(x, y);
        else ctx.lineTo(x, y);
      }
      ctx.strokeStyle = '#f472b6';
      ctx.stroke();

      // Current point
      const px = cx + A * Math.sin(a * trailEnd + delta) * scale;
      const py = cy - A * Math.sin(b * trailEnd) * scale;
      ctx.beginPath();
      ctx.arc(px, py, 5, 0, 2 * Math.PI);
      ctx.fillStyle = '#f472b6';
      ctx.fill();
      ctx.strokeStyle = '#fff';
      ctx.lineWidth = 1.5;
      ctx.stroke();
    }

    // Label
    ctx.fillStyle = '#8b8fa3';
    ctx.font = this._font(12);
    ctx.textAlign = 'right';
    ctx.fillText(`a:b = ${a}:${b}`, W - 16, 24);
  }
}

register(LissajousExploration);
