import { registerTrail } from './trail-registry.js';

registerTrail({
  id: 'fractal-worlds',
  title: 'Fractal Worlds',
  description: 'From simple triangles to the infinite complexity of the Mandelbrot set.',
  steps: [
    {
      explorationId: 'sierpinski',
      params: {},
      teaser: 'A triangle made of triangles',
      narrativeCallback: null,
    },
    {
      explorationId: 'affine-ifs',
      params: {},
      teaser: 'The chaos game',
      narrativeCallback: 'Sierpinski\'s triangle can be drawn by random jumps toward vertices. This "chaos game" generalizes to any set of affine maps.',
    },
    {
      explorationId: 'barnsley',
      params: {},
      teaser: 'A fern from four rules',
      narrativeCallback: 'Four affine maps, chosen with different probabilities, draw a perfect fern. Nature from mathematics.',
    },
    {
      explorationId: 'l-system',
      params: {},
      teaser: 'Plants from grammar rules',
      narrativeCallback: 'L-systems encode growth rules as strings. "F" means draw, "+" means turn. The simplest grammars produce realistic plants.',
    },
    {
      explorationId: 'mandelbrot',
      params: {},
      teaser: 'Infinite complexity from z²+c',
      narrativeCallback: 'From discrete IFS to continuous iteration. The Mandelbrot set is generated by the simplest possible feedback loop.',
    },
    {
      explorationId: 'julia-set',
      params: {},
      teaser: 'One set for every point',
      narrativeCallback: 'Every point in the Mandelbrot set defines a Julia set. Inside Mandelbrot: connected Julia. Outside: dust.',
    },
  ],
});
